# Generated by Django 2.1.1 on 2018-09-24 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('author_name', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
            ],
        ),
    ]
